config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  
  devise_scope :user do 
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    root to: "home#welcome"

    get 'schedules', to: 'home#schedules', as: 'all_schedules'
    get 'student_panel' , to: 'home#student_panel'

    namespace :admin do
      get 'home'
    end
    
    resources :schedule_items do
      delete 'attendee/:attendee_id', to: "schedule_items#remove_attendee", as: "remove_attendee"
      post 'attendee/:attendee_id', to: "schedule_items#add_attendee", as: "add_attendee"
    end

    get 'global/schedule', to: "schedule_items#global", as: 'global_schedule'
    
    resources :people do
      get 'schedule', to: "schedule_items#for_person"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def schedules
    @people = Person.all
    @kinds = Person.kinds.keys
  end

  def welcome
  end

  def student_panel
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% for kind in @kinds %> 
<h3><%= kind.humanize %></h3>
<ul class="list-group list-group-flush">
<% for person in @people.filter {|p| p.kind == kind} %>
  <%= link_to person_schedule_url(person.id), class: 'list-group-item list-group-item-action d-flex justify-content-between' do %>
    <%= person.name %>
    <div class="col-md-6 row">
        <div class="text-warning col-md-6">
            <% if person.missing_links.count > 0 %>
                <%= fa_icon "exclamation-triangle", text: " Zoom Links Missing", size: '1x', left: true %>
            <% end %>
        </div>
        <div class="text-danger col-md-6">
            <% if person.schedule_conflicts.count > 0 %>
                <%= fa_icon "exclamation-circle", text: " Conflicts detected", size: '1x', left: true %>
            <% end %>
        </div>
    </div>
  <% end %>
  </ul>
<%end%>
<%end%>

app/views/home/schedules.html.erb
<% for kind in @kinds %> 
<h3><%= kind.humanize %></h3>
<ul class="list-group list-group-flush">
<% for person in @people.filter {|p| p.kind == kind} %>
  <%= link_to person_schedule_url(person.id), class: 'list-group-item list-group-item-action d-flex justify-content-between' do %>
    <%= person.name %>
    <div class="col-md-6 row">
        <div class="text-warning col-md-6">
            <% if person.missing_links.count > 0 %>
                <%= fa_icon "exclamation-triangle", text: " Zoom Links Missing", size: '1x', left: true %>
            <% end %>
        </div>
        <div class="text-danger col-md-6">
            <% if person.schedule_conflicts.count > 0 %>
                <%= fa_icon "exclamation-circle", text: " Conflicts detected", size: '1x', left: true %>
            <% end %>
        </div>
    </div>
  <% end %>
  </ul>
<%end%>
<%end%>

app/views/home/student_panel.html.erb
<h1>Student Panel</h1>
<h4>Thursday at 5pm: <a href="https://ucsd.zoom.us/j/98286509509?pwd=eE9yK2J6MVhzUDhCZmFSczVEU2t0dz09">Zoom Link</a></h4>

<b>Ask questions live or in advance: <a href="https://app.sli.do/event/okaqiaph">Slido</a></b>
<br/>
<br/>

<p>The goal of the student panel is to answer any and all questions or concerns
you may have about non-research specific topics (Similar to the questions
that have been already posted on our Visit Day slack channel). These
questions can be broadly about topics such as housing, program
structure/coursework, funding, student life, support system (including
physical and mental health), or any other things you may have queries
about/want to discuss. The panel consists of current senior and junior PhD
students, with <b>no faculty or staff in attendance, and no recording of the
event</b>. Feel completely free to bring up any question/concern that you might
think of.

<p>We have two ways to post questions before/during the session:
Before the session, we will use this <a href="https://app.sli.do/event/okaqiaph">Slido forum to post questions</a>.
During the session we will still continue to use Slido preferably, but you can also post your questions to the panelists using the Zoom chat.

<p>If you have any questions, feel free to reach out to the organizers:<br/>
Nishant Bhaskar &lt;<a href="mailto:nibhaska@eng.ucsd.edu">nibhaska@eng.ucsd.edu</a>&gt;  or Dhiman Sengupta &lt;<a href="mailto:dhimnsen@eng.ucsd.edu">dhimnsen@eng.ucsd.edu</a>&gt;
<br/><br/>
Looking forward to interacting with all of you!!!!

app/views/home/welcome.html.erb
<h1> Welcome to UCSD Visit Day </h1>
<br />

<% images = Dir.children('public/slideshow').map {|i| "/slideshow/#{i}"}%>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" style="height: 480px">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <% images.each_with_index do |_, idx| %>
      <li data-target="#carouselExampleIndicators" data-slide-to="<%= idx %>"></li>
    <% end %>
  </ol>
  <div class="carousel-inner" style="height: 100%;">
    <% images.each_with_index do |img, idx| %>
      <div class="carousel-item <%= 'active' if idx == 0 %>" style="text-align: center; background: black">
        <img src="<%=img%>" style="height: 480px; object-fit: contain" loading="lazy"/>
      </div>
    <% end %>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<br />
<h3>Hello!</h3>
<br/>

<p>You are awesome and we want you to come to UCSD! It’s unfortunate that you
don’t get to see the campus and San Diego in person, but we hope that our
meetings will give you a glimpse into the excellent research you could be
doing at UCSD and the awesome community we have. 
</p>

<p>
Here, you will be able to see the schedules assigned to all attendees: these
include time slots with zoom links with the folks you will meet throughout
the day. Your name will be listed under the heading “Prospective” (you may
want to use ctrl-F to find yourself, since there are a lot of names); you can
click on your name to access your specific schedule for the visit days.
</p>

<p>
Beyond the one-on-ones and group meeting(s), we wanted to highlight three student events:
</p>

<ul>
<li><b>Diversity, equity and inclusion panel</b> on at Thu 1pm.
<li><b>Student panel</b> on Thu at 5pm (<%= link_to "more info", student_panel_url %>)
<li><b>Game night</b> on Fri at 5pm.
</ul>

<p>These events are informal, but likely informative and fun -- we encourage you
to attend!
<br/>

<p><b>We have a dedicated
<a href="https://join.slack.com/t/ucsdcsevisitday2021/shared_invite/zt-mq1qo4o1-Ra_QXMGgVwAvbIp2yyCecA">
  visit day slack
</a></b>
where you can hang out with us and other admits.

Finally, if you have any questions, comments, or concerns, please feel free
to ping your student buddy or the organizers (Deian &lt;<a href="mailto:deian@cs.ucsd.edu">deian@cs.ucsd.edu</a>&gt; and
Tierra &lt;<a href="mailto:tterrell@eng.ucsd.edu">tterrell@eng.ucsd.edu</a>&gt;) or ask on the visit day slack.
</p>
<br/>

Have fun!