config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  
  devise_scope :user do 
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    root to: "home#welcome"

    get 'schedules', to: 'home#schedules', as: 'all_schedules'
    get 'student_panel' , to: 'home#student_panel'

    namespace :admin do
      get 'home'
    end
    
    resources :schedule_items do
      delete 'attendee/:attendee_id', to: "schedule_items#remove_attendee", as: "remove_attendee"
      post 'attendee/:attendee_id', to: "schedule_items#add_attendee", as: "add_attendee"
    end

    get 'global/schedule', to: "schedule_items#global", as: 'global_schedule'
    
    resources :people do
      get 'schedule', to: "schedule_items#for_person"
    end
  end
end

app/models/schedule_item.rb
require 'active_support'
require 'active_support/core_ext/numeric/time'
class ScheduleItem < ApplicationRecord
    attribute :starts_at, :datetime, default: -> { ScheduleItem.start_date_time } 
    attribute :ends_at, :datetime, default: -> { ScheduleItem.start_date_time } 
    has_and_belongs_to_many :people

    def is_group_event?
        self.people.exists?(kind: :research_group)
    end

    def is_busy_time?
        self.people.count == 1
    end

    def missing_link?
        self.meeting_link.empty? && (not self.is_busy_time?)
    end

    def group_name
        self.people.where(kind: :research_group)[0].name
    end

    def event_date
        self.starts_at_date
    end

    def event_date=(date)
        self.starts_at_date=date
        self.ends_at_date=date
    end

    def starts_at_date=(date)
        date = Date.parse date
        self.starts_at = self.starts_at.change(:year=>date.year, :month=>date.month, :day=>date.day)
    end
    def starts_at_date
        self.starts_at.to_date
    end
    def ends_at_date=(date)
        date = Date.parse date
        self.ends_at = self.ends_at.change(:year=>date.year, :month=>date.month, :day=>date.day)
    end
    def ends_at_date
        self.ends_at.to_date
    end

    def starts_at_time=(time)
        time = Time.parse time
        self.starts_at = self.starts_at.change(:hour=>time.hour, :min=>time.strftime("%M").to_i)
    end
    def starts_at_time
        self.starts_at.to_s(:time)
    end
    def ends_at_time=(time)
        time = Time.parse time
        self.ends_at = self.ends_at.change(:hour=>time.hour, :min=>time.strftime("%M").to_i)
    end
    def ends_at_time
        self.ends_at.to_s(:time)
    end

    def with_person=(id)
        p = Person.find id
        self.people << p unless self.people.include? p
    end

    def author=(id)
        with_person=(id)
    end

    def self.group_events
        ScheduleItem.includes(:people)
                    .where('people.kind' => :research_group)
                    .order(starts_at: :asc, ends_at: :asc)
    end

    private
    def ScheduleItem.start_date_time
        t = Rails.configuration.x.start_time
        d = Rails.configuration.x.days[0]
        dt = DateTime.new(d.year, d.month, d.day, t.hour, t.min, t.sec, Time.zone_offset(t.zone))
    end
end

app/controllers/schedule_items_controller.rb
class ScheduleItemsController < ApplicationController
  before_action :authenticate_user!, except: [:for_person]
  before_action :get_person, only: [:for_person]
  before_action :get_author, only: [:create, :destroy, :update, :add_attendee, :remove_attendee]
  before_action :set_schedule_item, only: [:show, :edit, :update, :destroy, :remove_attendee, :add_attendee]
  before_action :schedule_item_params, only: [:create, :update]

  def global
    @schedule_item = ScheduleItem.new(is_global: true)
    @schedule_items = ScheduleItem.where(is_global: true)
  end

  def for_person
    @schedule_item = ScheduleItem.new
    @schedule_items = @person.schedule_items
    @all_people = Person.where.not(kind: :research_group)
    conflicts = @person.schedule_conflicts
    if conflicts.count > 0
      flash[:alert] = ""
      for p in conflicts
        if !flash.now[:alert].empty?
          flash.now[:alert] += "<br/>"
        end
        flash.now[:alert] += helpers.conflict_text(@person, p[0], p[1])
      end
    end
    @conflicts = conflicts.flatten
    @missing_links = @person.missing_links

    if @missing_links.count > 0
      flash[:notice] = ""
      for p in @missing_links
        if !flash.now[:notice].empty?
          flash.now[:notice] += "<br/>"
        end
        flash.now[:notice] += helpers.missing_link_text(@person, p)
      end
    end

    @group_meetings = ScheduleItem.group_events
  end

  def add_attendee
    @schedule_item.people << Person.find(params.require(:attendee_id))
    @schedule_item.save
    respond_to do |format|
      format.html { redirect_to redirect_url}
    end
  end
  
  def remove_attendee
    @schedule_item.people.delete(params.require(:attendee_id))
    @schedule_item.save
    respond_to do |format|
      format.html { redirect_to redirect_url}
    end
  end

  # GET /schedule_items/new
  def new
    @schedule_item = ScheduleItem.new
  end

  # POST /schedule_items
  # POST /schedule_items.json
  def create
    @schedule_item = ScheduleItem.new(schedule_item_params)
    if !@author.nil? && schedule_item_params[:with_person].to_i != @author.id
      @schedule_item.people << @author
    end
    respond_to do |format|
      if @schedule_item.save
        format.html { redirect_to redirect_url, notice: 'Schedule item was successfully created.' }
        format.json { render :show, status: :created, location: @schedule_item }
      else
        format.html { render :new }
        format.json { render json: @schedule_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedule_items/1
  # PATCH/PUT /schedule_items/1.json
  def update
    respond_to do |format|
      if @schedule_item.update(schedule_item_params)
        format.html { redirect_to redirect_url, notice: 'Schedule item was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule_item }
      else
        format.html { render :edit }
        format.json { render json: @schedule_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedule_items/1
  # DELETE /schedule_items/1.json
  def destroy
    @schedule_item.destroy!
    respond_to do |format|
      format.html { redirect_to redirect_url, notice: 'Schedule item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def redirect_url
      if !@author.nil?
        person_schedule_url(person_id: @author)
      else
        global_schedule_url
      end
    end

    def get_author
      maybe_author = params.permit(:author_id)[:author_id]
      @author = maybe_author.nil? ? nil : Person.find(maybe_author)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_schedule_item
      @schedule_item = ScheduleItem.find(params[:schedule_item_id] || params[:id])
    end

    # Only allow a list of trusted parameters through.
    def schedule_item_params
      params.require(:schedule_item).permit(:event_date, :with_person, :starts_at_time, :ends_at_time, :name, :location, :is_global, :meeting_link, :include_faculty)
    end

    def get_person
      @person = Person.find(params[:person_id])
    end
end

app/helpers/schedule_items_helper.rb
module ScheduleItemsHelper
end

app/views/schedule_items/_form.html.erb
<%
  clas = 'form-inline'
  if is_conflict
    clas += ' conflict'
  end
  if is_missing_link
    clas += ' missing_link'
  end
  author = nil if local_assigns[:author].nil?
  disabled = nil if local_assigns[:disabled].nil?

%>
<%= form_with(model: schedule_item, local: true, class: clas, namespace: schedule_item.id) do |form| %>
  <% if schedule_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(schedule_item.errors.count, "error") %> prohibited this schedule_item from being saved:</h2>

      <ul>
        <% schedule_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= form.hidden_field :is_global %>
    <% if !author.nil? %>
    <%= hidden_field_tag(:author_id, author&.id) %>
    <%end%>
    <div class="form-group col-md-10 row">
      <% if disabled %>
          <span class="col-auto" style="font-weight: bold">
            <%= schedule_item.starts_at.strftime("%b %e") %>
          </span>
          <div class="col-auto" style="font-weight: bold">
          <%= schedule_item.starts_at.strftime("%l:%M%p") %> - 
          <%= schedule_item.ends_at.strftime("%l:%M%p") %>
          (PST)
          </div>
      <% else %>
        <%= form.label :event_date, "Day", class: 'sr-only' %>
        <%= form.select :event_date, Rails.configuration.x.days, {}, {disabled: disabled, class: 'form-control custom-select form-inline col-auto'} %>
        <div class="col-auto">
        <div class="input-group" style="display: inline-block">
          <%= form.label :starts_at_time, "Start", class: 'sr-only' %>
          <%= form.time_field :starts_at_time, value: schedule_item.starts_at_time, disabled: disabled, class: 'form-control form-input-inline', required: 'required', autofocus: true %>
          <%= form.label :ends_at_time, "End", class: 'sr-only' %>
          <%= form.time_field :ends_at_time, value: schedule_item.ends_at_time, disabled: disabled, class: 'form-control form-input-inline', required: 'required' %>
        </div>
        (PST)
        </div>
      <% end %>
      <% if disabled %>
        <div class="col-auto"><b style=><%= string_name_for(author, schedule_item) %></b></div>
      <% elsif schedule_item.is_global || author&.research_group? %>
     
        <%= form.label :name, class: 'sr-only' %>
        <%= form.text_field :name, placeholder: "Event Name", class: 'form-control form-input-inline col-auto' %>
      
      <% elsif schedule_item.persisted? %>
        <% for attendee in schedule_item.people.all.filter {|a| a.id != author.id} %>
            <%= link_to schedule_item_remove_attendee_url(schedule_item, attendee, author_id: author.id), method: 'delete', class: "btn btn-secondary" do %>
              <%=attendee.name%>
              <span class="badge badge-secondary">
              x
              </span>
            <% end %>
            &nbsp;
        <% end %>
        <div class="dropdown" style="display:inline-block">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            +
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <% for attendee in all_people.filter {|p| !schedule_item.people.all.include? p} %>
              <%= link_to attendee.name,
                schedule_item_add_attendee_url(schedule_item, attendee.id, author_id: author.id),
                method: :post,
                class: "dropdown-item" %>
            <% end %>
          </div>
        </div>
      <% else %>
        <%= form.label :with_person, class: 'sr-only' %>
        <div class="input-group">
          <div class="input-group-prepend">
            <div class="input-group-text"><%=fa_icon('user')%></div>
          </div>
          <%= form.collection_select :with_person, all_people, :id, :name, {}, {class: 'form-control custom-select col-auto'} %>
        </div>
      <% end %>

    <% if disabled %>
      <span><%= Rinku.auto_link(schedule_item.meeting_link) {|_| "Zoom Meeting"}.html_safe %></span>
    <% else %>
      <div class="form-group col-11 row" style="margin-top: .5em">

      <%= form.text_field :meeting_link, placeholder:"Link (e.g. meet.google.com/adsfasdf)", disabled:disabled, class: "form-control col-8" %>
      <% if schedule_item.is_global %>
          <div class="form-check col-4">
            <%= form.check_box :include_faculty, {class: 'form-check-input' } %>
            <%= form.label :include_faculty, class: 'col-form-label'%>
          </div>
      <% end %>
      </div>
    <% end %>

    </div>
    <div class="form-group btn-group">
    <% if !disabled %>
      <%= button_tag type: 'submit', class: 'btn btn-primary' do %>
        <%= fa_icon "save", size: '1x' %>
      <% end %>

      <% if !schedule_item.new_record? %>
        <%= link_to schedule_item_url(schedule_item, author_id: author&.id), method: 'delete', class: 'btn btn-danger', data: { confirm: 'This will delete the event for all participants' } do %>
          <%= fa_icon "trash-alt", size: '1x' %>
        <% end %>
      <% end %>
    <% end %>

    <% if !author&.research_group? && schedule_item.is_group_event? && user_signed_in? %>
        <%= link_to schedule_item_remove_attendee_url(schedule_item, author.id, author_id: author.id), method: 'delete', class: 'btn btn-danger' do %>
          <%= fa_icon "sign-out-alt", size: '1x' %>
        <% end %>
    <% end %>
    </div>
<% end %>
<hr />

app/views/schedule_items/_global_row.html.erb
GLOBAL

app/views/schedule_items/edit.html.erb
<h1>Editing Schedule Item</h1>

<%= render 'form', schedule_item: @schedule_item %>

<%= link_to 'Show', @schedule_item %> |
<%= link_to 'Back', schedule_items_path %>

app/views/schedule_items/for_person.html.erb
<h1><%= @person.name %>'s Schedule</h1>

<% if user_signed_in? %>
<h3>New Event</h3>
<%= render "form", author: @person, schedule_item: @schedule_item, is_missing_link: false, is_conflict: false, all_people: @all_people %>
<% if !@person.research_group? %>
or 

<div class="dropdown" style="display:inline-block">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Add Group Meeting
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <% for gm in @group_meetings %>
      <%= link_to group_meeting_info(gm),
        schedule_item_add_attendee_url(gm, @person, author_id: @person),
        method: :post,
        class: "dropdown-item" %>
    <% end %>
  </div>
  </div>
  <%end %>
<br/>
<br />


<h3>Schedule Items</h3>
<% end %>
  <% @schedule_items.each do |schedule_item| %>
    <%= render "form", author: @person, schedule_item: schedule_item, all_people: @all_people, is_missing_link: schedule_item.missing_link?, is_conflict: (@conflicts.include? schedule_item), disabled: !user_signed_in? || schedule_item.is_global || (!@person.research_group? && schedule_item.is_group_event?)%>
  <% end %>

<br>

app/views/schedule_items/global.html.erb
<h1>Global's Schedule</h1>

<% if user_signed_in? %>
Events listed here are added to everyone's schedule

<h3>New Event</h3>
<%= render "form", schedule_item: @schedule_item, is_missing_link: false, is_conflict: false %>

<br/>
<br/>

<h3>Schedule Items</h3>
<% end %>
  <% @schedule_items.each do |schedule_item| %>
    <%= render "form", schedule_item: schedule_item, is_missing_link: schedule_item.missing_link?, is_conflict: false, disabled: !user_signed_in? %>
  <% end %>

<br>

app/views/schedule_items/new.html.erb
<h1>New Schedule Item</h1>

<%= render 'form', person: @person, schedule_item: @schedule_item %>

<%= link_to 'Back', person_schedule_items_path %>

app/views/schedule_items/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_schedule_item_path(@schedule_item) %> |
<%= link_to 'Back', schedule_items_path %>