config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  
  devise_scope :user do 
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    root to: "home#welcome"

    get 'schedules', to: 'home#schedules', as: 'all_schedules'
    get 'student_panel' , to: 'home#student_panel'

    namespace :admin do
      get 'home'
    end
    
    resources :schedule_items do
      delete 'attendee/:attendee_id', to: "schedule_items#remove_attendee", as: "remove_attendee"
      post 'attendee/:attendee_id', to: "schedule_items#add_attendee", as: "add_attendee"
    end

    get 'global/schedule', to: "schedule_items#global", as: 'global_schedule'
    
    resources :people do
      get 'schedule', to: "schedule_items#for_person"
    end
  end
end

app/views/layouts/_navbar.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm">
    <%= link_to 'Visit Day', root_url, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <%= link_to 'Schedules', all_schedules_url, class: 'nav-link' %>
        </li>
        <li class="nav-item">
            <%= link_to 'Student Panel', "/student_panel", class: 'nav-link' %>
        </li>
        <% if user_signed_in? %>
            <li class="nav-item">
                <%= link_to 'Global Events', global_schedule_url, class: 'nav-link' %>
            </li>
            <li class="nav-item">
                <%= link_to 'Manage People', people_url, class: 'nav-link' %>
            </li>
            <li class="nav-time">
                <%= link_to 'Invite Schedulers', new_user_invitation_url, class: 'nav-link' %>
            </li>
        <% end %>
        </ul>
        <ul class="navbar-nav">
        <li class="nav-item">
            <% if user_signed_in? %>
            <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'nav-link') %>        
            <% else %>
            <%= link_to('Login', new_user_session_path, class: 'nav-link') %>  
            <% end %>
        </li>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VisitDay</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: '/layouts/navbar' %>
    <div class="container pt-md-3">
    <% flash.each do |key, value| %>
      <div class="row flex-xl-nowrap <%= flash_class(key) %>">
        <%= raw(value) %>
      </div>
    <% end %>
    </div>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>